deployment:
  tasks:
    - export DEPLOYPATH=/home/tfeyykzm/public_html/
    - /bin/rsync -av --delete --exclude '.git' --exclude '.cpanel.yml' ./ $DEPLOYPATH
    - /usr/bin/find $DEPLOYPATH -type d -exec /bin/chmod 755 {} +
    - /usr/bin/find $DEPLOYPATH -type f -exec /bin/chmod 644 {} +
